node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     sh "npm -v" 
     sh "docker ps" 
     // don't need Global Tools anymore: nodejs(nodeJSInstallationName: 'nodejs') {
     sh 'npm install --only=dev'
     sh 'npm test'     
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("solvedshared/nodejs-demo:${commit_id}", '.').push()
     }
   }
   stage('docker run') {
      // If applicable - stop any running application
      try { 
         sh "docker stop my-nodejs-app" 
      } catch( Exception e) { 
      }
      // If applicable - remove any created container
      try { 
         sh "docker container rm my-nodejs-app" 
      } catch( Exception e) { 
      }
      
      sh "docker run -p 3000:3000 -d --name my-nodejs-app solvedshared/nodejs-demo:${commit_id}" 
   }
   
}
