node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
     // DIT KAN NIET: onbekend: sh "npm -v" 
     // OOK 'node -v' kan ie niet vinden. 
     // LET OP ... dit kan wel !! Logisch want die zit in de Jenkins IMAGE!
     sh "npm -v" 
     sh "docker ps" 
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("solvedshared/nodejs-demo:${commit_id}", '.').push()
     }
   }
   stage('docker run') {
     sh "docker run -p 3000:3000 -d --name my-nodejs-app solvedshared/nodejs-demo:${commit_id}" 
   }
   
}
